INSERT ALL
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'hi',NULL,NULL,NULL)
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'3-D Man',N'',N'2014-04-29T14:18:17-0400',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/c/e0/535fecbbb9784'', ''extension'': ''jpg''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'A-Bomb (HAS)',N'Rick Jones has been Hulk''s best bud since day one, but now he''s more than a friend...he''s a teammate! Transformed by a Gamma energy explosion, A-Bomb''s thick, armored skin is just as strong and powerful as it is blue. And when he curls into action, he use',N'2013-09-18T15:54:04-0400',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/3/20/5232158de5b16'', ''extension'': ''jpg''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'A.I.M.',N'AIM is a terrorist organization bent on destroying the world.',N'2013-10-17T14:41:30-0400',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/6/20/52602f21f29ec'', ''extension'': ''jpg''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Aaron Stack',N'',N'1969-12-31T19:00:00-0500',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available'', ''extension'': ''jpg''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Abomination (Emil Bl',N'Formerly known as Emil Blonsky, a spy of Soviet Yugoslavian origin working for the KGB, the Abomination gained his powers after receiving a dose of gamma radiation similar to that which transformed Bruce Banner into the incredible Hulk.',N'2012-03-20T12:32:12-0400',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/9/50/4ce18691cbf04'', ''extension'': ''jpg''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Abomination (Ultimat',N'',N'2012-07-10T19:11:52-0400',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available'', ''extension'': ''jpg''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Absorbing Man',N'',N'2013-10-24T14:32:08-0400',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/1/b0/5269678709fb7'', ''extension'': ''jpg''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Abyss',N'',N'2014-04-29T14:10:43-0400',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/9/30/535feab462a64'', ''extension'': ''jpg''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Abyss (Age of Apocal',N'',N'1969-12-31T19:00:00-0500',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/3/80/4c00358ec7548'', ''extension'': ''jpg''}')
SELECT 1 FROM DUAL;
INSERT ALL
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Adam Destine',N'',N'1969-12-31T19:00:00-0500',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available'', ''extension'': ''jpg''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Adam Warlock',N'Adam Warlock is an artificially created human who was born in a cocoon at a scientific complex called The Beehive.',N'2013-08-07T13:49:06-0400',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/a/f0/5202887448860'', ''extension'': ''jpg''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Aegis (Trey Rollins)',N'',N'1969-12-31T19:00:00-0500',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/5/e0/4c0035c9c425d'', ''extension'': ''gif''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Aero (Aero)',N'',N'2021-08-27T17:52:34-0400',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available'', ''extension'': ''jpg''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Agatha Harkness',N'',N'2021-08-06T11:30:56-0400',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/c/a0/4ce5a9bf70e19'', ''extension'': ''jpg''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Agent Brand',N'',N'2013-10-24T13:09:30-0400',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/4/60/52695285d6e7e'', ''extension'': ''jpg''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Agent X (Nijo)',N'Originally a partner of the mind-altering assassin Black Swan, Nijo spied on Deadpool as part of the Swan''s plan to exact revenge for Deadpool falsely taking credit for the Swan''s assassination of the Four Winds crime family, which included Nijo''s brother',N'1969-12-31T19:00:00-0500',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available'', ''extension'': ''jpg''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Agent Zero',N'',N'1969-12-31T19:00:00-0500',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/f/60/4c0042121d790'', ''extension'': ''jpg''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Agents of Atlas',N'',N'2016-02-03T10:25:22-0500',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/9/a0/4ce18a834b7f5'', ''extension'': ''jpg''}')
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Aginar',N'',N'1969-12-31T19:00:00-0500',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available'', ''extension'': ''jpg''}')
SELECT 1 FROM DUAL;
INSERT ALL
	INTO libreria.dbo.[character] (name,description,modified,thumbnail) VALUES (N'Air-Walker (Gabriel ',N'',N'1969-12-31T19:00:00-0500',N'{''path'': ''http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available'', ''extension'': ''jpg''}')
SELECT 1 FROM DUAL;INSERT ALL
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,52952,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
SELECT 1 FROM DUAL;
INSERT ALL
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
SELECT 1 FROM DUAL;
INSERT ALL
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Marvel Previews (2017)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Marvel Previews (2017)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Marvel Previews (2017)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,52952,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Marvel Age Spider-Man Vol. 2: Everyday Hero (Digest)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Sentry, the (Trade Paperback)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Gun Theory (2003) #4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Ant-Man (2003) #4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Ant-Man (2003) #1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Ant-Man (2003) #3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Official Handbook of the Marvel Universe (2004) #11 (X-MEN - AGE OF APOCALYPSE)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
SELECT 1 FROM DUAL;
INSERT ALL
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'ULTIMATE X-MEN VOL. 5: ULTIMATE WAR TPB (Trade Paperback)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'X-Men: Days of Future Past (Trade Paperback)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Amazing Spider-Man 500 Covers Slipcase - Book II (Trade Paperback)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Storm (2006)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Gun Theory (2003) #3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Official Handbook of the Marvel Universe (2004) #9 (THE WOMEN OF MARVEL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Startling Stories: The Incorrigible Hulk (2004) #1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Official Handbook of the Marvel Universe (2004) #13 (TEAMS)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Official Handbook of the Marvel Universe (2004) #10 (MARVEL KNIGHTS)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Ant-Man (2003) #2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
SELECT 1 FROM DUAL;
INSERT ALL
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Marvel Previews (2017)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Marvel Previews (2017)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Marvel Previews (2017)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,52952,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Marvel Age Spider-Man Vol. 2: Everyday Hero (Digest)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Sentry, the (Trade Paperback)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Gun Theory (2003) #4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Ant-Man (2003) #4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Ant-Man (2003) #1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Ant-Man (2003) #3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Official Handbook of the Marvel Universe (2004) #11 (X-MEN - AGE OF APOCALYPSE)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,11,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
SELECT 1 FROM DUAL;
INSERT ALL
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'ULTIMATE X-MEN VOL. 5: ULTIMATE WAR TPB (Trade Paperback)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'X-Men: Days of Future Past (Trade Paperback)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Amazing Spider-Man 500 Covers Slipcase - Book II (Trade Paperback)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Storm (2006)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Gun Theory (2003) #3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Official Handbook of the Marvel Universe (2004) #9 (THE WOMEN OF MARVEL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,9,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Startling Stories: The Incorrigible Hulk (2004) #1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Official Handbook of the Marvel Universe (2004) #13 (TEAMS)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,13,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Official Handbook of the Marvel Universe (2004) #10 (MARVEL KNIGHTS)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Ant-Man (2003) #2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
SELECT 1 FROM DUAL;
INSERT ALL
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Marvel Previews (2017)',N'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'2019-11-07T08:46:15-0500',N'',NULL,0,0,N'',N'75960608839302811',N'',N'',N'',N'',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Marvel Previews (2017)',N'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'2019-08-21T17:11:27-0400',N'',NULL,0,0,N'',N'75960608839302611',N'JUL190068',N'',N'',N'',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Marvel Previews (2017)',N'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'2020-02-07T09:35:32-0500',N'',NULL,52952,0,N'',N'75960608839303111',N'',N'',N'',N'',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Marvel Age Spider-Man Vol. 2: Everyday Hero (Digest)',N'"The Marvel Age of Comics continues! This time around, Spidey meets his match against such classic villains as Electro and the Lizard, and faces the return of one of his first foes: the Vulture! Plus: Spider-Man vs. the Living Brain, Peter Parker''s fight ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'2018-01-22T15:42:11-0500',N'0-7851-1451-3',NULL,0,0,N'',N'5960611451-00111',N'',N'',N'',N'Digest',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Sentry, the (Trade Paperback)',N'On the edge of alcoholism and a failed marriage, Bob Reynolds wakes up to discover his true nature. A forgotten hero, he must unravel the conspiracy to erase his memory from mankind before an evil entity returns.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'0-7851-0799-1',NULL,0,0,N'',N'',N'',N'',N'',N'Trade Paperback',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Gun Theory (2003) #4',N'The phone rings, and killer-for-hire Harvey embarks on another hit. But nothing''s going right this job. There''s little room for error in the business of killing - so what happens when one occurs?
32 PGS./ PARENTAL ADVISORY ...$2.50',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',NULL,0,4,N'',N'5960605468-00111',N'',N'',N'',N'Comic',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Ant-Man (2003) #4',N'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',NULL,0,4,N'',N'5960605482-00411',N'',N'',N'',N'Comic',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Ant-Man (2003) #1',N'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',NULL,0,1,N'',N'5960605396-01811',N'',N'',N'',N'Comic',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Ant-Man (2003) #3',N'When Hank Pym - a.k.a. Ant-Man - is tapped by U.S. Intelligence to infiltrate an international spy ring that has been siphoning secrets out of Washington, the diminutive hero jumps at the chance - unaware that he''s being used as a pawn in a larger game of',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',NULL,0,3,N'',N'5960605396-02011',N'',N'',N'',N'Comic',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Official Handbook of the Marvel Universe (2004) #11 (X-MEN - AGE OF APOCALYPSE)',N'Your complete guide to the epic saga! This Official Handbook includes in-depth bios on more than 40 denizens of the Age of Apocalypse - from Abyss to Weapon X! Plus: An all-new cover by superstar-in-waiting Mark Brooks, digitally painted by Justin Ponsor.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',NULL,0,11,N'X-MEN - AGE OF APOCALYPSE',N'5960605625-00111',N'',N'',N'',N'Comic',NULL,NULL)
SELECT 1 FROM DUAL;
INSERT ALL
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'ULTIMATE X-MEN VOL. 5: ULTIMATE WAR TPB (Trade Paperback)',N'The Ultimates vs. the Ultimate X-Men: the battle begins. When the X-Men do the worst thing they could to humanity, the government orders Captain America, Iron Man, Thor and the rest of the Ultimates to bring them down. A small but lethal army, the Ultimat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'2018-03-12T16:56:16-0400',N'0-7851-1129-8',NULL,0,0,N'',N'',N'',N'',N'',N'Trade Paperback',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'X-Men: Days of Future Past (Trade Paperback)',N'"Re-live the legendary first journey into the dystopian future of 2013 - where Sentinels stalk the Earth, and the X-Men are humanity''s only hope...until they die! Also featuring the first appearance of Alpha Flight, the return of the Wendigo, the history ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'2017-02-28T14:52:22-0500',N'0-7851-1560-9',NULL,0,0,N'',N'5960611560-00111',N'',N'',N'',N'Trade Paperback',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Amazing Spider-Man 500 Covers Slipcase - Book II (Trade Paperback)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',NULL,0,0,N'',N'',N'',N'',N'',N'Trade Paperback',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Storm (2006)',N'The epic, untold love story between Marvel''s two pre-eminent Black super heroes -- Storm and the Black Panther -- is finally told, as only New York Times best-selling author Eric Jerome Dickey can do it!  An orphaned street urchin, living by her wits on t',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'2015-01-29T20:04:55-0500',N'',NULL,0,0,N'',N'',N'',N'',N'',N'Comic',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Gun Theory (2003) #3',N'The phone rings, and killer-for-hire Harvey embarks on another hit. But nothing''s going right this job. There''s little room for error in the business of killing - so what happens when one occurs?

32 PGS./ PARENTAL ADVISORY ...$2.50',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',NULL,0,3,N'',N'5960605492-00411',N'',N'',N'',N'Comic',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Official Handbook of the Marvel Universe (2004) #9 (THE WOMEN OF MARVEL)',N'Marvel''s leading ladies take center stage! This Official Handbook includes in-depth bios on more than 40 of the House''s most powerful women warriors - from Araña to Vindicator! Plus: an all-new cover by superstar artist Greg Land!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',NULL,0,9,N'THE WOMEN OF MARVEL',N'5960605678-00111',N'',N'',N'',N'Comic',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Startling Stories: The Incorrigible Hulk (2004) #1',N'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',NULL,0,1,N'',N'5960605429-00811',N'',N'',N'',N'Comic',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Official Handbook of the Marvel Universe (2004) #13 (TEAMS)',N'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',NULL,0,13,N'TEAMS',N'5960605695-00111',N'',N'',N'',N'Comic',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Official Handbook of the Marvel Universe (2004) #10 (MARVEL KNIGHTS)',N'On the mean streets of the Marvel Universe, the kid gloves come off. Guardian devils, vengeance-seeking vigilantes and enigmatic assassins stalk the city''s dark underbelly _ and the urban action unfolds with gritty intensity. The newest entry in Marvel''s ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',NULL,0,10,N'MARVEL KNIGHTS',N'5960605694-00111',N'',N'',N'',N'Comic',NULL,NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Ant-Man (2003) #2',N'Ant-Man digs deeper to find out who is leaking secret information that threatens our national security.
32 pgs./PARENTAL ADVISORY...$2.99',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',NULL,0,2,N'',N'5960605396-01911',N'',N'',N'',N'Comic',NULL,NULL)
SELECT 1 FROM DUAL;
INSERT ALL
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Marvel Previews (2017)',N'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'2019-11-07T08:46:15-0500',N'',112,0,0,N'',N'75960608839302811',N'',N'',N'',N'',N'[]',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Marvel Previews (2017)',N'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'2019-08-21T17:11:27-0400',N'',152,0,0,N'',N'75960608839302611',N'JUL190068',N'',N'',N'',N'[]',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Marvel Previews (2017)',N'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'2020-02-07T09:35:32-0500',N'',112,52952,0,N'',N'75960608839303111',N'',N'',N'',N'',N'[]',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Marvel Age Spider-Man Vol. 2: Everyday Hero (Digest)',N'"The Marvel Age of Comics continues! This time around, Spidey meets his match against such classic villains as Electro and the Lizard, and faces the return of one of his first foes: the Vulture! Plus: Spider-Man vs. the Living Brain, Peter Parker''s fight ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'2018-01-22T15:42:11-0500',N'0-7851-1451-3',96,0,0,N'',N'5960611451-00111',N'',N'',N'',N'Digest',N'[{''type'': ''issue_solicit_text'', ''language'': ''en-us'', ''text'': ''"The Marvel Age of Comics continues! This time around, Spidey meets his match against such classic villains as Electro and the Lizard, and faces the return of one of his first foes: the Vulture',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Sentry, the (Trade Paperback)',N'On the edge of alcoholism and a failed marriage, Bob Reynolds wakes up to discover his true nature. A forgotten hero, he must unravel the conspiracy to erase his memory from mankind before an evil entity returns.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'0-7851-0799-1',240,0,0,N'',N'',N'',N'',N'',N'Trade Paperback',N'[{''type'': ''issue_solicit_text'', ''language'': ''en-us'', ''text'': ''On the edge of alcoholism and a failed marriage, Bob Reynolds wakes up to discover his true nature. A forgotten hero, he must unravel the conspiracy to erase his memory from mankind before an e',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Gun Theory (2003) #4',N'The phone rings, and killer-for-hire Harvey embarks on another hit. But nothing''s going right this job. There''s little room for error in the business of killing - so what happens when one occurs?
32 PGS./ PARENTAL ADVISORY ...$2.50',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',0,0,4,N'',N'5960605468-00111',N'',N'',N'',N'Comic',N'[{''type'': ''issue_solicit_text'', ''language'': ''en-us'', ''text'': "The phone rings, and killer-for-hire Harvey embarks on another hit. But nothing''s going right this job. There''s little room for error in the business of killing - so what happens when one occur',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Ant-Man (2003) #4',N'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',0,0,4,N'',N'5960605482-00411',N'',N'',N'',N'Comic',N'[{''type'': ''issue_solicit_text'', ''language'': ''en-us'', ''text'': "Ant-Man digs deeper into finding out who is leaking those dirty little secrets that are threatening our national security. And who''s better at uncovering dirty LITTLE secrets than him??"}]',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Ant-Man (2003) #1',N'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',0,0,1,N'',N'5960605396-01811',N'',N'',N'',N'Comic',N'[{''type'': ''issue_solicit_text'', ''language'': ''en-us'', ''text'': "Size does matter.  And no one knows this more than Hank Pym - a.k.a. Ant-Man. Got a problem with Galactus? Call the FF. Got a problem with, say, mind-controlled cockroaches? Then Ant-Man''s your',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Ant-Man (2003) #3',N'When Hank Pym - a.k.a. Ant-Man - is tapped by U.S. Intelligence to infiltrate an international spy ring that has been siphoning secrets out of Washington, the diminutive hero jumps at the chance - unaware that he''s being used as a pawn in a larger game of',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',0,0,3,N'',N'5960605396-02011',N'',N'',N'',N'Comic',N'[{''type'': ''issue_solicit_text'', ''language'': ''en-us'', ''text'': "When Hank Pym - a.k.a. Ant-Man - is tapped by U.S. Intelligence to infiltrate an international spy ring that has been siphoning secrets out of Washington, the diminutive hero jumps at the chanc',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Official Handbook of the Marvel Universe (2004) #11 (X-MEN - AGE OF APOCALYPSE)',N'Your complete guide to the epic saga! This Official Handbook includes in-depth bios on more than 40 denizens of the Age of Apocalypse - from Abyss to Weapon X! Plus: An all-new cover by superstar-in-waiting Mark Brooks, digitally painted by Justin Ponsor.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',0,0,11,N'X-MEN - AGE OF APOCALYPSE',N'5960605625-00111',N'',N'',N'',N'Comic',N'[{''type'': ''issue_solicit_text'', ''language'': ''en-us'', ''text'': ''Your complete guide to the epic saga! This Official Handbook includes in-depth bios on more than 40 denizens of the Age of Apocalypse - from Abyss to Weapon X! Plus: An all-new cover by superst',NULL)
SELECT 1 FROM DUAL;
INSERT ALL
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'ULTIMATE X-MEN VOL. 5: ULTIMATE WAR TPB (Trade Paperback)',N'The Ultimates vs. the Ultimate X-Men: the battle begins. When the X-Men do the worst thing they could to humanity, the government orders Captain America, Iron Man, Thor and the rest of the Ultimates to bring them down. A small but lethal army, the Ultimat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'2018-03-12T16:56:16-0400',N'0-7851-1129-8',112,0,0,N'',N'',N'',N'',N'',N'Trade Paperback',N'[{''type'': ''issue_solicit_text'', ''language'': ''en-us'', ''text'': "The Ultimates vs. the Ultimate X-Men: the battle begins. When the X-Men do the worst thing they could to humanity, the government orders Captain America, Iron Man, Thor and the rest of the Ulti',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'X-Men: Days of Future Past (Trade Paperback)',N'"Re-live the legendary first journey into the dystopian future of 2013 - where Sentinels stalk the Earth, and the X-Men are humanity''s only hope...until they die! Also featuring the first appearance of Alpha Flight, the return of the Wendigo, the history ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'2017-02-28T14:52:22-0500',N'0-7851-1560-9',144,0,0,N'',N'5960611560-00111',N'',N'',N'',N'Trade Paperback',N'[{''type'': ''issue_solicit_text'', ''language'': ''en-us'', ''text'': ''"Re-live the legendary first journey into the dystopian future of 2013 - where Sentinels stalk the Earth, and the X-Men are humanity\''s only hope...until they die! Also featuring the first appe',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Amazing Spider-Man 500 Covers Slipcase - Book II (Trade Paperback)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',0,0,0,N'',N'',N'',N'',N'',N'Trade Paperback',N'[]',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Storm (2006)',N'The epic, untold love story between Marvel''s two pre-eminent Black super heroes -- Storm and the Black Panther -- is finally told, as only New York Times best-selling author Eric Jerome Dickey can do it!  An orphaned street urchin, living by her wits on t',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'2015-01-29T20:04:55-0500',N'',0,0,0,N'',N'',N'',N'',N'',N'Comic',N'[{''type'': ''issue_solicit_text'', ''language'': ''en-us'', ''text'': "The epic, untold love story between Marvel''s two pre-eminent Black super heroes -- Storm and the Black Panther -- is finally told, as only New York Times best-selling author Eric Jerome Dickey ',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Gun Theory (2003) #3',N'The phone rings, and killer-for-hire Harvey embarks on another hit. But nothing''s going right this job. There''s little room for error in the business of killing - so what happens when one occurs?

32 PGS./ PARENTAL ADVISORY ...$2.50',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',0,0,3,N'',N'5960605492-00411',N'',N'',N'',N'Comic',N'[{''type'': ''issue_solicit_text'', ''language'': ''en-us'', ''text'': "The phone rings, and killer-for-hire Harvey embarks on another hit. But nothing''s going right this job. There''s little room for error in the business of killing - so what happens when one occur',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Official Handbook of the Marvel Universe (2004) #9 (THE WOMEN OF MARVEL)',N'Marvel''s leading ladies take center stage! This Official Handbook includes in-depth bios on more than 40 of the House''s most powerful women warriors - from Araña to Vindicator! Plus: an all-new cover by superstar artist Greg Land!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',0,0,9,N'THE WOMEN OF MARVEL',N'5960605678-00111',N'',N'',N'',N'Comic',N'[{''type'': ''issue_solicit_text'', ''language'': ''en-us'', ''text'': "Marvel''s leading ladies take center stage! This Official Handbook includes in-depth bios on more than 40 of the House''s most powerful women warriors - from Araña to Vindicator! Plus: an all-new',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Startling Stories: The Incorrigible Hulk (2004) #1',N'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',0,0,1,N'',N'5960605429-00811',N'',N'',N'',N'Comic',N'[{''type'': ''issue_solicit_text'', ''language'': ''en-us'', ''text'': ''For Doctor Bruce Banner life is anything but normal. But what happens when two women get between him and his alter ego, the Incorrigible Hulk? Hulk confused! \r\nIndy superstar Peter Bagge (THE',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Official Handbook of the Marvel Universe (2004) #13 (TEAMS)',N'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',0,0,13,N'TEAMS',N'5960605695-00111',N'',N'',N'',N'Comic',N'[{''type'': ''issue_solicit_text'', ''language'': ''en-us'', ''text'': "Heavy-hitting heroes unite! This Official Handbook contains in-depth bios on more than 30 of the Marvel Universe''s most awesome assemblages - including the Defenders, Power Pack and the New Thu',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Official Handbook of the Marvel Universe (2004) #10 (MARVEL KNIGHTS)',N'On the mean streets of the Marvel Universe, the kid gloves come off. Guardian devils, vengeance-seeking vigilantes and enigmatic assassins stalk the city''s dark underbelly _ and the urban action unfolds with gritty intensity. The newest entry in Marvel''s ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',0,0,10,N'MARVEL KNIGHTS',N'5960605694-00111',N'',N'',N'',N'Comic',N'[{''type'': ''issue_solicit_text'', ''language'': ''en-us'', ''text'': "On the mean streets of the Marvel Universe, the kid gloves come off. Guardian devils, vengeance-seeking vigilantes and enigmatic assassins stalk the city''s dark underbelly _ and the urban actio',NULL)
	INTO libreria.dbo.comics (title,description,[image],url,id_type,id_creator,id_genre,avaliable,price,quantity,modified,isbn,pagecount,digitalid,issuenumber,variantDescription,upc,diamondCode,ean,issn,format,textObjects,resorceURI) VALUES (N'Ant-Man (2003) #2',N'Ant-Man digs deeper to find out who is leaking secret information that threatens our national security.
32 pgs./PARENTAL ADVISORY...$2.99',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'-0001-11-30T00:00:00-0500',N'',0,0,2,N'',N'5960605396-01911',N'',N'',N'',N'Comic',N'[{''type'': ''issue_solicit_text'', ''language'': ''en-us'', ''text'': ''Ant-Man digs deeper to find out who is leaking secret information that threatens our national security.\r\n32 pgs./PARENTAL ADVISORY...$2.99''}]',NULL)
SELECT 1 FROM DUAL;